"use client";
import React from "react";

function Page() {
  return (
    <div>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
      <p>HEllo</p>
    </div>
  );
}

export default Page;
