export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;

export const USER_INFO_ID =
  process.env.NEXT_PUBLIC_APPWRITE_USERINFO_COLLECTION!;
export const ADMIN_INVITE_TOKEN_ID =
  process.env.NEXT_PUBLIC_APPWRITE_INVITEADMINTOKEN_COLLECTION!;

export const IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
